### ISSUE TITLE
undefined mapping: als_Latn

### ISSUE THREAD

**Issue by fatjoni** [pluiez/NLLB-inference#3]
I am experiencing a problem when trying to translate from albania to english bash translate.sh /content/checkpoint.pt als_Latn  eng_Latn  <<< 'Ku eshte qeni o doktor?'  

I receive  undefined mapping: als_Latn
This happens on my machine with this model as well https://tinyurl.com/nllb200dense3bcheckpoint   and only when translating from albanian language  to another language, not vice versa. Any idea?

**Comment by pluiez** [comment]
Hi, the missing languages will use English by default. For details please check the related issue on stopes.

**Comment by fatjoni** [comment]
Thanks a lot, just tested it and it finally works :')
