### ISSUE TITLE
simple question about nllb-inference 

### ISSUE THREAD

**Issue by daje0601** [pluiez/NLLB-inference#4]
Hello, I saw your youtube and github code. 
So Thank you! 

Thanks to this, I was able to run it in Colab. When I ran it, I was able to observe that it showed really good performance.

I want to customize this bash code to python. 
bash is so hard.. 
Can you tell me how to fix this code in python?
If that's difficult, can you explain how this code works?

please merry on me

**Comment by daje0601** [comment]
First of all, I really thank you for your response. 
I agree that Bash script is great. I will learn bash script later. 

What I'm thinking about it that bash script always reload the model I want to just language translation.
I don't catch how can I fix it?  I'm still thinking..

**Comment by pluiez** [comment]
> First of all, I really thank you for your response. I agree that Bash script is great. I will learn bash script later.
> 
> �What I'm thinking about it that bash script always reload the model I want to just language translation. I don't catch how can I fix it? I'm still thinking..

Do you mean you want to load a model and then change the langauges later for translation?

**Comment by daje0601** [comment]
> > First of all, I really thank you for your response. I agree that Bash script is great. I will learn bash script later.
> > What I'm thinking about it that bash script always reload the model I want to just language translation. I don't catch how can I fix it? I'm still thinking..
> 
> Do you mean you want to load a model and then change the langauges later for translation?

Yes!  Exactly!

**Comment by daje0601** [comment]
Actually, I am a junior who has only been learning Python for a year. 
However, we are growing by challenging myself as much as possible.

**Comment by pluiez** [comment]
> > > First of all, I really thank you for your response. I agree that Bash script is great. I will learn bash script later.
> > > What I'm thinking about it that bash script always reload the model I want to just language translation. I don't catch how can I fix it? I'm still thinking..
> > 
> > 
> > Do you mean you want to load a model and then change the langauges later for translation?
> 
> Yes! Exactly!

You can check this https://stackoverflow.com/questions/66525973/running-fairseq-in-memory-and-pre-load-language-models

**Comment by daje0601** [comment]
Thank you!
